
ROLE_CUSTOMER_MANAGER = "manager"
ROLE_CUSTOMER_USER = "stream"

# Actions

# All Role Actions
ROLE_ALL_ACTION = [
    ROLE_CUSTOMER_MANAGER,
    ROLE_CUSTOMER_USER
]

ROLE_MANAGER_USER_ACTION = ROLE_ALL_ACTION

ROLE_CUSTOMER_USER_ACTION = [ROLE_CUSTOMER_USER]
