OFFLINE_CONTROLLER_BASE_PATH = "/api/v1/offline"

OFFLINE_REVIEW_RATING_AVERAGE_PATH = OFFLINE_CONTROLLER_BASE_PATH + "/average-product-review-rating"
OFFLINE_CATEGORY_REVENUE_PATH = OFFLINE_CONTROLLER_BASE_PATH + "/category-revenue"
OFFLINE_PRODUCT_REVENUE_PATH = OFFLINE_CONTROLLER_BASE_PATH + "/product-revenue"
OFFLINE_SOLD_PRODUCT_UNITS_PATH = OFFLINE_CONTROLLER_BASE_PATH + "/sold-product-units"
