STREAM_CONTROLLER_BASE_PATH = "/api/v1/stream"

STREAM_REVIEW_RATING_AVERAGE_PATH = STREAM_CONTROLLER_BASE_PATH + "/review-rating-average"
STREAM_LAST_PURCHASE_AMOUNT_PATH = STREAM_CONTROLLER_BASE_PATH + "/customer-last-purchase-amount"
STREAM_LAST_CUSTOMER_PRODUCT_REVIEW_PATH = STREAM_CONTROLLER_BASE_PATH + "/customer-last-product-review-rating"
STREAM_TOTAL_REVENUE_BY_CATEGORY_PATH = STREAM_CONTROLLER_BASE_PATH + "/total-revenue-by-category"
