errors = {
    1000: "Model validation error",
    1100: "Unprocessable entity",
    1101: "Could not contact provider service",
    1200: "Not Authenticated",
    1201: "Permission Denied",
    1300: "Infra Exceptions",
    1400: "Connection error to the database",
    1999: "Unhandled error",
    2000: "Queue connection lost",
    2001: "Unexpected error for Queue",
    2002: "Publish event unexpected error",
    2003: "Product reviews rating average with the given product id is not found",
    2004: "Customer last purchase amount with the given customer id is not found",
    2005: "Customer last product review rating with the given customer id and product id is not found",
    2006: "Total revenue by category with the given category is not found",
    2007: "Last month product reviews rating average with the given product id is not found",
    2008: "Last month category revenue with the given category is not found",
    2009: "Last month product revenue with the given product id is not found",
    2010: "Last month sold product units with the given product id is not found",
}
